### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by loveinmyheart** [AxeChen/retrofit2_rxjava2#1]
我参考你的demo完成了封装，效果都实现了，但是有一个地方不同，就是你可以直接得到实体类对象，但是我的返回是一个Object 还需要自己强转，每次都写，感觉不太好，请问你知道什么原因吗。
RetrofitManager.getIMGoldBird().getMineNoLoginRecommendGoods(map)
                    .compose(this.<Response<GoodsBean>>bindToLifecycle())//管理Retrofit的生命周期  当页面被销毁时取消网络请求 防止内存泄露
                    .compose(ResponseTransformer.<GoodsBean>handleResult())
                    .compose(schedulerProvider.applySchedulers())
                    .subscribeOn(Schedulers.io())
                    .doOnSubscribe(new Consumer<Disposable>() {
                        @Override
                        public void accept(@NonNull Disposable disposable) throws Exception {
                            //此方法是在事件发起之前做的准备工作  例：网络请求发起的ProgressBar转圈
                        }
                    })
                    .subscribeOn(AndroidSchedulers.mainThread())//指定主线程
                    .observeOn(Schedulers.io())
                    .doOnNext(new Consumer<Object>() {
                        @Override
                        public void accept(@NonNull Object o) throws Exception {
                            //doOnNext:数据输出准备  一般用于网络获取数据后缓存到数据库  因为数据库操作是耗时操作所以需要在子线程进行
                            GoodsBean gb= (GoodsBean) o;
                            cacheDoubleUtils.put("sp",gb);//缓存
                        }
                    })
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(new Observer<Object>() {
                        @Override
                        public void onSubscribe(Disposable disposable) {

                        }

                        @Override
                        public void onNext(Object obj) {
                            GoodsBean goodsBean= (GoodsBean) obj;
                            if (goodsBean!=null){
                                if (data.size()>0){
                                    data.clear();
                                }
                                data.addAll(goodsBean.getRows());
                                adapter.notifyDataSetChanged();
                            }
                        }

                        @Override
                        public void onError(Throwable throwable) {
                            ApiException apiException= (ApiException) throwable;
                            ToastUtils.showLong("onError: "+"加载失败了"+apiException.getCode()+apiException.getDisplayMessage());
                        }

                        @Override
                        public void onComplete() {

                        }
                    });

**Comment by AxeChen** [comment]
我的Response用了泛型 你那边用到了吗？

**Comment by loveinmyheart** [comment]
感谢回复  ！！！
用了泛型的
private int state;//返回码
private T data;//数据
private String message;//后台消息提示


public T getData() {
    return data;
}

public void setData(T data) {
    this.data = data;
}

public String getMessage() {
    return message;
}

public void setMessage(String message) {
    this.message = message;
}

public int getState() {
    return state;
}

public void setState(int state) {
    this.state = state;
}






------------------ 原始邮件 ------------------
发件人: "再峰"<notifications@github.com>; 
发送时间: 2019年8月27日(星期二) 下午4:39
收件人: "AxeChen/retrofit2_rxjava2"<retrofit2_rxjava2@noreply.github.com>; 
抄送: "Smile at life"<32531242@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [AxeChen/retrofit2_rxjava2] 提问 (#1)




我的Response用了泛型 你那边用到了吗？
