### ISSUE TITLE
问

### ISSUE THREAD

**Issue by loveinmyheart** [AxeChen/retrofit2_rxjava2#2]
我尝试完全模仿你的demo来，发现还是会出这样的问题  
只有Object才不会报错  如果是用T对应的实体类对象就会报错
public class Presenter {

    private Model model;

    private Contract.View view;

    private BaseSchedulerProvider schedulerProvider;

    private CompositeDisposable mDisposable;

    public Presenter(Model model,
                     Contract.View view,
                     BaseSchedulerProvider schedulerProvider) {
        this.model = model;
        this.view = view;
        this.schedulerProvider = schedulerProvider;
        mDisposable = new CompositeDisposable();

    }

    public void despose(){
        mDisposable.dispose();
    }

    public void getList() {
        Map<String,String> map=new HashMap<>();
        map.put("current_page",1+"");
        map.put("list_rows","10");
        Disposable disposable = model.getGoodsList(map)
                .compose(ResponseTransformer.<GoodsBean>handleResult())
                .compose(schedulerProvider.applySchedulers())
                .subscribe(new Consumer<Object>() {
                               @Override
                               public void accept(Object carBeans) throws Exception {
                                   // 处理数据 直接获取到

                               }
                           }, new Consumer<Throwable>() {
                               @Override
                               public void accept(Throwable throwable) throws Exception {
                                   // 处理异常
                               }
                           }

                );

        mDisposable.add(disposable);
    }

}

**Comment by AxeChen** [comment]
```    
  // 初始化Retrofit
        retrofit = new Retrofit.Builder()
                .client(client)
                .baseUrl(Request.HOST)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();
```
这个GsonConverterFactory你有用到吗？
