### ISSUE TITLE
3 有用到的

### ISSUE THREAD

**Issue by loveinmyheart** [AxeChen/retrofit2_rxjava2#3]
OkHttpClient.Builder builder=new  OkHttpClient.Builder();
        builder.connectTimeout(15, TimeUnit.SECONDS);//设置网络连接超时时间
        builder.readTimeout(15, TimeUnit.SECONDS);//设置数据读取超时时间
        builder.writeTimeout(15, TimeUnit.SECONDS);//设置数据写入超时时间

        OkHttpClient client=builder.build();

        retrofit = new Retrofit.Builder()
                .client(client)
                .baseUrl(APIManage.BASE_URL)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())//使用Rxjava的Observable方式必须添加此项  使用Retrofit默认Call形式则不需要
                .addConverterFactory(GsonConverterFactory.create())//将服务器返回的json数据转换为实体类对象
                .build();

**Comment by AxeChen** [comment]
15601953341 我的微信 微信上聊吧
