### ISSUE TITLE
非200的的返回码信息，ApiException在哪里获取呢？

### ISSUE THREAD

**Issue by ixiongpeng** [AxeChen/retrofit2_rxjava2#5]
你好，根据你的代码，已经能成功获取正常数据。但非200返回码的信息ApiException在哪里获取呢？谢谢指导

**Comment by AxeChen** [comment]
感谢支持！
在response包目录下面有一个ResponseTransformer.java
 /**
     * 服务其返回的数据解析
     * 正常服务器返回数据和服务器可能返回的exception
     *
     * @param <T&gt;
     */
    private static class ResponseFunction<T&gt; implements Function<Response<T&gt;, ObservableSource<T&gt;&gt; {
 
        @Override
        public ObservableSource<T&gt; apply(Response<T&gt; tResponse) throws Exception {
            int code = tResponse.getCode();
            String message = tResponse.getMsg();
            if (code == 200) {
                return Observable.just(tResponse.getData());
            } else {
                return Observable.error(new ApiException(code, message));
            }
        }
    } 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AxeChen/retrofit2_rxjava2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 中午11:38
收件人:&nbsp;"AxeChen/retrofit2_rxjava2"<retrofit2_rxjava2@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[AxeChen/retrofit2_rxjava2] 非200的的返回码信息，ApiException在哪里获取呢？ (#5)





 
你好，根据你的代码，已经能成功获取正常数据。但非200返回码的信息ApiException在哪里获取呢？谢谢指导
